# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('viddate', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('unknown', models.IntegerField(max_length=1)),
                ('action', models.IntegerField(max_length=1)),
                ('adventure', models.IntegerField(max_length=1)),
                ('animation', models.IntegerField(max_length=1)),
                ('childrens', models.IntegerField(max_length=1)),
                ('comedy', models.IntegerField(max_length=1)),
                ('crime', models.IntegerField(max_length=1)),
                ('documentary', models.IntegerField(max_length=1)),
                ('drama', models.IntegerField(max_length=1)),
                ('fantasy', models.IntegerField(max_length=1)),
                ('film_noir', models.IntegerField(max_length=1)),
                ('horror', models.IntegerField(max_length=1)),
                ('musical', models.IntegerField(max_length=1)),
                ('mystery', models.IntegerField(max_length=1)),
                ('romance', models.IntegerField(max_length=1)),
                ('sci_fi', models.IntegerField(max_length=1)),
                ('thriller', models.IntegerField(max_length=1)),
                ('war', models.IntegerField(max_length=1)),
                ('western', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('movieid', models.IntegerField(unique=True)),
                ('rating', models.IntegerField()),
                ('time', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('occupation', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField(max_length=20)),
                ('avg', models.FloatField()),
            ],
        ),
    ]
