# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avg',
            field=models.FloatField(default=0.0),
        ),
    ]
