# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160909_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movieid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='userid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
